version: "3.8"
services:
  app:
    container_name: DRINKWATER
    build: '.'
    volumes:
      - ./:/usr/app
      - ./node_modules:/usr/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8000'
  db:
    image: 'mongo'
    container_name: MONGODB
    ports:
      - '27117:27017'
    volumes:
      - ./data/db:/data/db
    restart: always